<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-09 10:15
=======
# Generated by Django 5.2.6 on 2025-09-09 10:05
>>>>>>> e7e30b9bf6e4833e8f25e46e9acad501b9714b39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
=======
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
>>>>>>> e7e30b9bf6e4833e8f25e46e9acad501b9714b39
            ],
        ),
    ]
