# Generated by Django 5.2.6 on 2025-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
